version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - mvn -Dmaven.test.skip=true clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'target'
 

 