logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
    root: ALL
    
cognito:
  url: ${COGNITO_URL}
  key: ${COGNITO_KEY}
    
spring:
  profiles:
    active: ${DEPLOYMENT_STAGE:dev}
  application:
    name: survey-service

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD:amazing1}
    url: ${DB_URL}
    username: ${DB_USERNAME:ptt5039}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:survey_service}
    show-sql: false
---
spring:
  profiles: test    

server:
  port: 8092
 
---
spring:
  profiles: dev    

server:
  port: 8092
  
user-service:
  ribbon:
    listOfServers: ${GATEWAY_URL:http://localhost:8765}

---
spring:
  profiles: prod

server:
  port: 5000
  
    
user-service:
  ribbon:
    listOfServers: ${GATEWAY_URL}
    

