logging:
  level:
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
    root: warn
    
cognito:
  url: ${COGNITO_URL}
  key: ${COGNITO_KEY}
    
spring:
  profiles: 
    active: dev #${DEPLOYMENT_STAGE}
  application:
    name: survey-service
  datasource:
   driver-class-name: org.h2.Driver
   platform: h2
   url: jdbc:h2:mem:data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
   username: sa
   password:
  #datasource:
   # driverClassName: org.postgresql.Driver
    #initialization-mode: NEVER
   # password: ${DB_PASSWORD}
   # url: ${DB_URL}
    #username: ${DB_USERNAME}
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  #  generate-ddl: false
  #  hibernate:
  #    ddl-auto: none
  #  properties:
  #    hibernate:
  #      default_schema: ${DB_SCHEMA}
    show-sql: false
  main:
   allow-bean-definition-overriding: true
    
---

      
spring:
  profiles: dev    

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 30
    
---
spring:
  profiles: dev

server:
  port: 8092
  

    
user-service:
  ribbon:
    #listOfServers: ${GATEWAY_URL}
    

